SYNTAX     ::= ( PRODUCTION )*
PRODUCTION ::= IDENTIFIER <EQUALS> EXPRESSION "."
EXPRESSION ::= TERM ( <BAR> TERM )*
TERM       ::= FACTOR+
FACTOR     ::= IDENTIFIER
           | LITERAL
           | <LBRACKET> EXPRESSION <RBRACKET>
           | <LPAREN> EXPRESSION <RPAREN>
           | <LBRACE> EXPRESSION <RBRACE>
IDENTIFIER ::= <LETTER>
LITERAL    ::= <QUOT> <CHARACTER>+ <QUOT>

